title: Minhyuk Sung
url: 'https://mhsung.github.io/'
#baseurl: '/example' #change it according to your repository name
permalink: none

#Profile information
name: Minhyuk Sung
tagline: Assistant Professor<br>School of Computing<br>KAIST
#pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mhsung@kaist.ac.kr
website: mhsung.github.io/ #do not add http://
linkedin: mhsung
github: mhsung
google_scholar: scholar.google.com/citations?user=PcIYMp4AAAAJ&hl=en
cv: cv/sung_cv.pdf
research_statement: assets/files/sung-sig19-dc.pdf

# Tracker
analytics: UA-35688210-1
#Update all the sections by editing the files inside _includes folder.

# Build settings
markdown: kramdown
